# script to convert the sqlite file into a python list so it can be used by heroku
from database import Database
from rich.progress import track


def main():
    database = Database("mysqlite3.db", "characters")
    last = 101759
    file = open("backend/db.py", "w")
    file.write("#file generated by converter.py \n")
    file.write("from database import Character \n")
    file.write("listCharacterObject = [ ")
    for i in track(range(1, last), description="generating db.py from mysqlite3.db..."):
        actualObject = database.returnCharacterById(i)
        file.write(
            f"""Character({actualObject.id}, {actualObject.eye_color}, {actualObject.hair_color}, {actualObject.age}, {actualObject.sex}, {actualObject.hair_lenght}, "{actualObject.image[40:len(actualObject.image)]}", "{actualObject.name.replace('"', "")}", {actualObject.mimikko}, {actualObject.clothing}, {actualObject.nsfw})""")
        if i != last:
            file.write(",")
    file.write("]")


if __name__ == "__main__":
    main()
